name: teleglobal_operate
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  cloud_firestore: ^5.0.0
  countries_world_map: ^1.3.0
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.1.0
  firebase_core: ^3.0.0
  flutter:
    sdk: flutter
  flutter_map: ^7.0.1
  flutter_map_cancellable_tile_provider: ^3.0.0
  font_awesome_flutter: ^10.7.0
  get: 4.6.6
  google_fonts: ^6.2.1
  latlong2: ^0.9.1

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
