// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPJE027Hu3I3LPsSNMYVKRIfmqoi_HD0A',
    appId: '1:632462924764:web:b27a741b5be4d43dc78d19',
    messagingSenderId: '632462924764',
    projectId: 'tgop-b4519',
    authDomain: 'tgop-b4519.firebaseapp.com',
    storageBucket: 'tgop-b4519.appspot.com',
    measurementId: 'G-YW8JJTYJ3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChndRwDygfTHl5Vu-7PDVGaxyAp9WzWL4',
    appId: '1:632462924764:android:19b9367a784647aac78d19',
    messagingSenderId: '632462924764',
    projectId: 'tgop-b4519',
    storageBucket: 'tgop-b4519.appspot.com',
  );
}
